import 'dart:convert';

class MockISACData {
  mockDashboard() {
    var res = {
      "DashboardData": {
        "BusinessOwnerApprovedRequestsCount": 104,
        "BusinessOwnerPendingRequestsCount": 7,
        "BusinessOwnerRejectedRequestsCount": 1,
        "GenericIDOwnerApprovedRequestsCount": 0,
        "GenericIDOwnerPendingRequestsCount": 0,
        "GenericIDOwnerRejectedRequestsCount": 0,
        "IdentityStoreID": null,
        "SelfApprovedRequestsCount": 13,
        "SelfPendingRequestsCount": 1,
        "SelfRejectedRequestsCount": 13,
        "SupervisorApprovedRequestsCount": 192,
        "SupervisorPendingRequestsCount": 6,
        "SupervisorRejectedRequestsCount": 2,
        "ThirdPartyApprovedRequestsCount": 2,
        "ThirdPartyPendingRequestsCount": 12,
        "ThirdPartyRejectedRequestsCount": 24,
        "VendorApprovedRequestsCount": 234,
        "VendorPendingRequestsCount": 55,
        "VendorRejectedRequestsCount": 34
      },
      "ResponseMessage": null,
      "ReturnStatus": 2
    };
    return json.encode(res);
  }

  mockRequestList() {
    var res = {
      "ResponseMessage": null,
      "ReturnListData": [
        {
          "ApplicationName": "ACS",
          "Branch_Code": "04989",
          "ENC_FormID": "uL8MOWuFkV5g+J/r5bpXqg==",
          "ENC_RequestID": "5aJwuOhW5KpbxQ8ugBfIdA==",
          "ENC_RequestTicketTypeID": "TU0390n1PJIqYCUt1yK7KA==",
          "EmpCode": "A9086",
          "Emp_Name": "Amogh Samant",
          "Environment": null,
          "EnvironmentColor": null,
          "IsForApproval": 1,
          "ModifiedDate": null,
          "ReasonDesc": null,
          "RequestEntryDate": "21 Sep 2024",
          "RequestID": 3157640,
          "RequestStatusID": 3,
          "RequestTicketTypeID": 1,
          "TemplateName": null,
          "TicketNumber": "1-04989-M-21SEP2024000011",
          "TicketStatus": null,
          "TypeOfRequest": "Modify",
          "isAuth": true
        },
        {
          "ApplicationName": "AD Group Management",
          "Branch_Code": "04989",
          "ENC_FormID": "jIQU0TOeYPaIUMkjqvd+7A==",
          "ENC_RequestID": "ZdhaWW5Ihblh5tpZi6dJrw==",
          "ENC_RequestTicketTypeID": "YWYsBjD9N492QL1nWG29Ug==",
          "EmpCode": "A9086",
          "Emp_Name": "Amogh Samant",
          "Environment": null,
          "EnvironmentColor": null,
          "IsForApproval": 1,
          "ModifiedDate": null,
          "ReasonDesc": null,
          "RequestEntryDate": "21 Sep 2024",
          "RequestID": 3157641,
          "RequestStatusID": 3,
          "RequestTicketTypeID": 1,
          "TemplateName": null,
          "TicketNumber": "1-04989-M-21SEP2024000012",
          "TicketStatus": null,
          "TypeOfRequest": "Modify",
          "isAuth": true
        },
        {
          "ApplicationName": "AD Group Management",
          "Branch_Code": "04989",
          "ENC_FormID": "MnE/bgH9zoPz53b61h6mUg==",
          "ENC_RequestID": "fl8E0cTCGpzoOOGzUoWvjA==",
          "ENC_RequestTicketTypeID": "Ryc7Yb/NLKPXDuQzTyr01w==",
          "EmpCode": "A9086",
          "Emp_Name": "Amogh Samant",
          "Environment": null,
          "EnvironmentColor": null,
          "IsForApproval": 1,
          "ModifiedDate": null,
          "ReasonDesc": null,
          "RequestEntryDate": "21 Sep 2024",
          "RequestID": 3157642,
          "RequestStatusID": 3,
          "RequestTicketTypeID": 1,
          "TemplateName": null,
          "TicketNumber": "1-04989-M-21SEP2024000013",
          "TicketStatus": null,
          "TypeOfRequest": "Modify",
          "isAuth": true
        },
        {
          "ApplicationName": "ACS",
          "Branch_Code": "04989",
          "ENC_FormID": "ULUBusz8JIcnH5fAPovaXw==",
          "ENC_RequestID": "voKp2vdsdp9oeXSp6Uipfg==",
          "ENC_RequestTicketTypeID": "rhafN1cn+LOmWPQUeFwjWQ==",
          "EmpCode": "A9086",
          "Emp_Name": "Amogh Samant",
          "Environment": null,
          "EnvironmentColor": null,
          "IsForApproval": 1,
          "ModifiedDate": null,
          "ReasonDesc": null,
          "RequestEntryDate": "21 Sep 2024",
          "RequestID": 3157643,
          "RequestStatusID": 3,
          "RequestTicketTypeID": 1,
          "TemplateName": null,
          "TicketNumber": "1-04989-N-21SEP2024000014",
          "TicketStatus": null,
          "TypeOfRequest": "Enable",
          "isAuth": true
        },
        {
          "ApplicationName": "ACS",
          "Branch_Code": "04989",
          "ENC_FormID": "qf5DUhkF9DWz1jovsCOAUA==",
          "ENC_RequestID": "P1j3VpZ8ELaWq5OKLpCYIQ==",
          "ENC_RequestTicketTypeID": "F4nrwpOi5v6koHV08OD2zg==",
          "EmpCode": "A9086",
          "Emp_Name": "Amogh Samant",
          "Environment": null,
          "EnvironmentColor": null,
          "IsForApproval": 1,
          "ModifiedDate": null,
          "ReasonDesc": null,
          "RequestEntryDate": "21 Sep 2024",
          "RequestID": 3157644,
          "RequestStatusID": 3,
          "RequestTicketTypeID": 1,
          "TemplateName": null,
          "TicketNumber": "1-04989-E-21SEP2024000015",
          "TicketStatus": null,
          "TypeOfRequest": "Unlock ID",
          "isAuth": true
        },
        {
          "ApplicationName": "ACS",
          "Branch_Code": "04989",
          "ENC_FormID": "njxMqHu8prxLWR0XYekO/Q==",
          "ENC_RequestID": "gmDKVBHA327AFJQuGl7QsA==",
          "ENC_RequestTicketTypeID": "tpwKwjCCvmthYTjH2ZLAJA==",
          "EmpCode": "A9086",
          "Emp_Name": "Amogh Samant",
          "Environment": null,
          "EnvironmentColor": null,
          "IsForApproval": 1,
          "ModifiedDate": null,
          "ReasonDesc": null,
          "RequestEntryDate": "21 Sep 2024",
          "RequestID": 3157645,
          "RequestStatusID": 3,
          "RequestTicketTypeID": 1,
          "TemplateName": null,
          "TicketNumber": "1-04989-D-21SEP2024000016",
          "TicketStatus": null,
          "TypeOfRequest": "Delete",
          "isAuth": true
        },
        {
          "ApplicationName": "LOS",
          "Branch_Code": "04989",
          "ENC_FormID": "Qr/s4Zje52GrGfK1Un7isg==",
          "ENC_RequestID": "dz+i0U7vio6TriMOwPXt0Q==",
          "ENC_RequestTicketTypeID": "YN5oPD2V7jkMOXqD18nHfQ==",
          "EmpCode": "A9086",
          "Emp_Name": "Amogh Samant",
          "Environment": null,
          "EnvironmentColor": null,
          "IsForApproval": 1,
          "ModifiedDate": null,
          "ReasonDesc": null,
          "RequestEntryDate": "21 Sep 2024",
          "RequestID": 3157648,
          "RequestStatusID": 3,
          "RequestTicketTypeID": 1,
          "TemplateName": null,
          "TicketNumber": "1-04989-M-21SEP2024000019",
          "TicketStatus": null,
          "TypeOfRequest": "Modify",
          "isAuth": true
        },
        {
          "ApplicationName": "Pennants Lending Factory",
          "Branch_Code": "04989",
          "ENC_FormID": "1hVWHax/U7YDNfGf6xvcug==",
          "ENC_RequestID": "tewyoAhg7PMxUlLeD2Refw==",
          "ENC_RequestTicketTypeID": "QqiKiPpu+DajhWzohy0LpA==",
          "EmpCode": "A9086",
          "Emp_Name": "Amogh Samant",
          "Environment": null,
          "EnvironmentColor": null,
          "IsForApproval": 1,
          "ModifiedDate": null,
          "ReasonDesc": null,
          "RequestEntryDate": "23 Sep 2024",
          "RequestID": 3157793,
          "RequestStatusID": 3,
          "RequestTicketTypeID": 1,
          "TemplateName": "WRM operations",
          "TicketNumber": "1-04989-A-23SEP2024000094",
          "TicketStatus": null,
          "TypeOfRequest": "Create",
          "isAuth": true
        },
        {
          "ApplicationName": "HDFC Individual Loan Processing System",
          "Branch_Code": "04989",
          "ENC_FormID": "kAfGysvY99neEfDKPr3Jpw==",
          "ENC_RequestID": "Tlyb38w/QwETaf4si0oq9Q==",
          "ENC_RequestTicketTypeID": "QEXZLKsZPdssx2/ZScoSGQ==",
          "EmpCode": "P8732",
          "Emp_Name": "Pankaj More",
          "Environment": null,
          "EnvironmentColor": null,
          "IsForApproval": 1,
          "ModifiedDate": null,
          "ReasonDesc": null,
          "RequestEntryDate": "30 Sep 2024",
          "RequestID": 3213225,
          "RequestStatusID": 3,
          "RequestTicketTypeID": 1,
          "TemplateName": "UAM LOANS CHECKER",
          "TicketNumber": "1-04989-A-30SEP2024000001",
          "TicketStatus": null,
          "TypeOfRequest": "Create",
          "isAuth": true
        },
        {
          "ApplicationName": "DIGI COLLECT",
          "Branch_Code": "04989",
          "ENC_FormID": "pAM4qQeB6ZYoi0Bpy8IG7A==",
          "ENC_RequestID": "JmAXxgqT0EwE+tLMUEZIKg==",
          "ENC_RequestTicketTypeID": "lENsDi9ajpUnwisp31RmPQ==",
          "EmpCode": "A9086",
          "Emp_Name": "Amogh Samant",
          "Environment": null,
          "EnvironmentColor": null,
          "IsForApproval": 1,
          "ModifiedDate": null,
          "ReasonDesc": null,
          "RequestEntryDate": "04 Oct 2024",
          "RequestID": 3213453,
          "RequestStatusID": 3,
          "RequestTicketTypeID": 1,
          "TemplateName": null,
          "TicketNumber": "1-04989-M-04OCT2024000019",
          "TicketStatus": null,
          "TypeOfRequest": "Modify",
          "isAuth": true
        }
      ],
      "ReturnStatus": 2
    };
    return json.encode(res);
  }

  mockRequestDetail() {
    var res = {
      "ResponseMessage": "Request has already been processed!",
      "ReturnStatus": 2,
      "TicketData": {
        "AccessType": 0,
        "ActionBy": null,
        "Agency": "",
        "AlternateText": null,
        "Application": "VDI VPN",
        "ApplicationID": 3610,
        "BandName": "D3 & Above",
        "BranchCode": "",
        "BranchCodeID": 0,
        "BusinessApprEmpCode": 0,
        "BusinessApprList": [
          {"EmpCode": 0, "EmpName": "--Select--"}
        ],
        "BusinessApproverName": "",
        "CPAAgencyId": 0,
        "ChangeApprover": null,
        "CompanyId": 0,
        "CostCode": "",
        "CostCodeID": 0,
        "CurrentApprover": "Vishal Muttoo (V0037)",
        "CurrentBranchCode": null,
        "CurrentSystemTemplate": null,
        "DefaultPasswordid": null,
        "Duration": 0,
        "EmailID": "",
        "Emp_Name": null,
        "FileUploadTempGuid": null,
        "FormID": 1,
        "FunctionApprEmpCode": 0,
        "GeneratePassword": false,
        "GenericIDOwnerEmpCode": null,
        "GenericIDOwnerEmpName": " ()",
        "HubId": 0,
        "HubName": "",
        "HubNameRemove": "",
        "HubRemoveId": 0,
        "IdentityStoreId": 0,
        "IdentityStoreMaster": {
          "Band": 0,
          "BandName": null,
          "BranchCode": "04989",
          "BranchCodeID": 0,
          "BranchName": "KANJUR MARG",
          "CompanyID": 4,
          "CompanyName": "HDFC Bank",
          "CompanyTypeId": 1,
          "ContactNumber": null,
          "CostCenterName": "WB Business Solution Group",
          "CostCode": "00069",
          "CostCodeID": 0,
          "DOJ": "/Date(1289154600000+0530)/",
          "EmailId": "abhishekv.parab@hdfcbank.com",
          "EmpActiveDirectoryID": "D2994",
          "EmpCode": "D2994",
          "Emp_Name": "Dinesh Kate",
          "IdentityFeedReferenceID": 19611,
          "IdentityStoreID": 0,
          "LastWorkingDate": null,
          "StatusID": true,
          "SupervisorEmpCode": "M2148",
          "SystemUserIDDesc": null,
          "VBMSCode": null,
          "cCheckerId": null,
          "cMakerId": null,
          "dCheckerDate": null,
          "dMakerDate": null
        },
        "MstApplicationAttributesValuesList": [
          {
            "DataDisplayValue": "INTERNET VDI",
            "DataMemberValue": null,
            "FieldId": 8269,
            "FieldName": "Access Required (INTERNET VDI)",
            "FieldType": 2,
            "FieldValueId": 0
          },
          {
            "DataDisplayValue": "Year",
            "DataMemberValue": null,
            "FieldId": 30696,
            "FieldName": "Type of Duration (Days)",
            "FieldType": 2,
            "FieldValueId": 0
          },
          {
            "DataDisplayValue": "2Year",
            "DataMemberValue": null,
            "FieldId": 30697,
            "FieldName": "Duration required",
            "FieldType": 2,
            "FieldValueId": 0
          },
          {
            "DataDisplayValue": "Extension period for Active staff",
            "DataMemberValue": null,
            "FieldId": 31895,
            "FieldName": "Justification for VPN Access",
            "FieldType": 2,
            "FieldValueId": 0
          }
        ],
        "NewGenericIDOwner": null,
        "PasswordLength": 8,
        "ProductCategoryId": 0,
        "ProductCategoryName": "",
        "ProductCategoryNameRemove": "",
        "ProductCategoryRemoveId": 0,
        "ProductId": 0,
        "ProductName": "",
        "ProductNameRemove": "",
        "ProductRemoveId": 0,
        "ReasonDesc": null,
        "ReasonForChange": null,
        "ReceipientID": 0,
        "RegionBranchId": "",
        "RegionBranchIdRemove": "",
        "RegionBranchRemoveId": null,
        "RegionId": 0,
        "RegionName": "",
        "RegionNameRemove": "",
        "RegionRemoveId": 0,
        "RejectReasonList": [
          {
            "AndroidSource": null,
            "CategoryDesc": null,
            "CategoryId": 0,
            "IOSSource": null,
            "IsEnable": null,
            "Reason_Desc": "--Select Reason--",
            "WINSource": null,
            "bAuthorised": false,
            "cAuthStatus": null,
            "cMakerId": null,
            "cRejectRemarks": null,
            "cid": 0,
            "dMakerDate": null
          },
          {
            "AndroidSource": null,
            "CategoryDesc": null,
            "CategoryId": 0,
            "IOSSource": null,
            "IsEnable": null,
            "Reason_Desc": "Invalid Request",
            "WINSource": null,
            "bAuthorised": false,
            "cAuthStatus": null,
            "cMakerId": null,
            "cRejectRemarks": null,
            "cid": 41,
            "dMakerDate": null
          },
          {
            "AndroidSource": null,
            "CategoryDesc": null,
            "CategoryId": 0,
            "IOSSource": null,
            "IsEnable": null,
            "Reason_Desc": "Invalid Rights",
            "WINSource": null,
            "bAuthorised": false,
            "cAuthStatus": null,
            "cMakerId": null,
            "cRejectRemarks": null,
            "cid": 42,
            "dMakerDate": null
          },
          {
            "AndroidSource": null,
            "CategoryDesc": null,
            "CategoryId": 0,
            "IOSSource": null,
            "IsEnable": null,
            "Reason_Desc": "Other",
            "WINSource": null,
            "bAuthorised": false,
            "cAuthStatus": null,
            "cMakerId": null,
            "cRejectRemarks": null,
            "cid": 0,
            "dMakerDate": null
          }
        ],
        "Remarks": "",
        "RequestEntryDate": null,
        "RequestID": 2946123,
        "RequestStatusID": 3,
        "RequestTicketMISDetailsList": [
          {
            "ActionBy": "Dinesh Kate - D2994",
            "RequestEntryDate": "/Date(1704187248077+0530)/",
            "Status_Desc": "Submitted to approver"
          },
          {
            "ActionBy": "Vishal Muttoo - V0037",
            "RequestEntryDate": "/Date(1718739555523+0530)/",
            "Status_Desc": "Rejected by approver"
          }
        ],
        "RequestType": 2,
        "RequestTypeValue": "Modify",
        "RequestorID": 19612,
        "ShowAuth": "",
        "ShowiSacPword": null,
        "StaffCode": null,
        "StateId": 0,
        "StateName": "",
        "StateNameRemove": "",
        "StateRemoveId": 0,
        "Status_Desc": null,
        "SupervisorOverRide": false,
        "SupervisorOverRideReasonID": 0,
        "SupervisorOverRideReasonList": [
          {
            "AndroidSource": null,
            "CategoryDesc": null,
            "CategoryId": 0,
            "IOSSource": null,
            "IsEnable": null,
            "Reason_Desc": "--Select--",
            "WINSource": null,
            "bAuthorised": false,
            "cAuthStatus": null,
            "cMakerId": null,
            "cRejectRemarks": null,
            "cid": 0,
            "dMakerDate": null
          },
          {
            "AndroidSource": null,
            "CategoryDesc": null,
            "CategoryId": 0,
            "IOSSource": null,
            "IsEnable": null,
            "Reason_Desc": "Supervisor on Leave",
            "WINSource": null,
            "bAuthorised": false,
            "cAuthStatus": null,
            "cMakerId": null,
            "cRejectRemarks": null,
            "cid": 47,
            "dMakerDate": null
          },
          {
            "AndroidSource": null,
            "CategoryDesc": null,
            "CategoryId": 0,
            "IOSSource": null,
            "IsEnable": null,
            "Reason_Desc": "Supervisor in Meeting / Training",
            "WINSource": null,
            "bAuthorised": false,
            "cAuthStatus": null,
            "cMakerId": null,
            "cRejectRemarks": null,
            "cid": 48,
            "dMakerDate": null
          },
          {
            "AndroidSource": null,
            "CategoryDesc": null,
            "CategoryId": 0,
            "IOSSource": null,
            "IsEnable": null,
            "Reason_Desc": "Other",
            "WINSource": null,
            "bAuthorised": false,
            "cAuthStatus": null,
            "cMakerId": null,
            "cRejectRemarks": null,
            "cid": 57,
            "dMakerDate": null
          }
        ],
        "SupervisorOverRideReasonOther": null,
        "SystemTemplateID": 0,
        "SystemUserID": "D2994",
        "SystemUserIDDesc": null,
        "TicketNumber": "24-04989-M-02JAN2024000203",
        "VBMSCode": null,
        "VendorCode": null,
        "VendorCompany": null,
        "iSacPwordGenerated": null,
        "isCritical": false,
        "isGenericID": false,
        "systemTemplate": null
      }
    };
    return json.encode(res);
  }

  mockRejectReason() {
    var res = {
      "ResponseMessage": null,
      "ReturnReasonData": [
        {
          "AndroidSource": null,
          "CategoryDesc": null,
          "CategoryId": 0,
          "IOSSource": null,
          "IsEnable": null,
          "Reason_Desc": "Invalid Request",
          "WINSource": null,
          "bAuthorised": false,
          "cAuthStatus": null,
          "cMakerId": null,
          "cRejectRemarks": null,
          "cid": 43,
          "dMakerDate": null
        },
        {
          "AndroidSource": null,
          "CategoryDesc": null,
          "CategoryId": 0,
          "IOSSource": null,
          "IsEnable": null,
          "Reason_Desc": "Invalid Rights",
          "WINSource": null,
          "bAuthorised": false,
          "cAuthStatus": null,
          "cMakerId": null,
          "cRejectRemarks": null,
          "cid": 44,
          "dMakerDate": null
        },
        {
          "AndroidSource": null,
          "CategoryDesc": null,
          "CategoryId": 0,
          "IOSSource": null,
          "IsEnable": null,
          "Reason_Desc": "Other",
          "WINSource": null,
          "bAuthorised": false,
          "cAuthStatus": null,
          "cMakerId": null,
          "cRejectRemarks": null,
          "cid": 0,
          "dMakerDate": null
        }
      ],
      "ReturnStatus": 2
    };
    return json.encode(res);
  }
}
